---
- name: Ensure RPC snooper service directory exists
  file:
    path: "/docker/{{ rpc_snooper_service_name }}"
    state: directory
    owner: "dockremap"
    group: "docker"
    mode: 0750

- name: Create compose file
  template:
    src: 'docker-compose.yml.j2'
    dest: '{{ rpc_snooper_compose_path }}'
    owner: 'dockremap'
    group: 'docker'
    mode: 0640

- name: Create containers
  community.docker.docker_compose_v2:
    project_src: '{{ rpc_snooper_service_path }}'
    files: '{{ rpc_snooper_compose_path | basename }}'
    state: '{{ compose_state }}'
    recreate: '{{ compose_recreate }}'
    pull: '{{ compose_pull }}'